import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import LoginForm from "./login";
import RegisterForm from "./register";
import { Button } from "@/components/ui/button";
export default function AuthPage() {
    const [mode, setMode] = useState("login");
    return (_jsxs("div", { className: "relative flex h-screen w-full overflow-hidden bg-gray-100", children: [_jsx("div", { className: "flex h-full w-full items-center justify-center px-6 md:hidden", children: mode === "login" ? (_jsx(LoginForm, { onSwitch: () => setMode("register") })) : (_jsx(RegisterForm, { onSwitch: () => setMode("login") })) }), _jsxs("div", { className: "hidden h-full w-full md:flex", children: [_jsx("div", { className: "relative z-10 flex w-1/2 items-center justify-center px-20", children: mode === "login" && (_jsx(LoginForm, { onSwitch: () => setMode("register") })) }), _jsx("div", { className: "relative z-10 flex w-1/2 items-center justify-center px-20", children: mode === "register" && (_jsx(RegisterForm, { onSwitch: () => setMode("login") })) }), _jsx("div", { className: `absolute top-0 left-0 flex h-full w-1/2 flex-col items-center justify-center bg-[#152D64] p-10 text-white transition-transform duration-700 ease-out ${mode === "login" ? "translate-x-full" : "translate-x-0"} `, style: { zIndex: 40 }, children: mode === "login" ? (_jsxs(_Fragment, { children: [_jsx("h2", { className: "mb-4 text-4xl font-bold", children: "Hello Friend!" }), _jsx("p", { className: "opacity-80", children: "Daftar sekarang, siap-siap jadi lebih pintar!" }), _jsx(Button, { variant: "outline", className: "mt-6 border-white text-black hover:bg-white hover:text-[#152D64]", onClick: () => setMode("register"), children: "Daftar Sekarang" })] })) : (_jsxs(_Fragment, { children: [_jsx("h2", { className: "mb-4 text-4xl font-bold", children: "Welcome Back!" }), _jsx("p", { className: "opacity-80", children: "Masuk sekarang dan lanjutkan belajar!" }), _jsx(Button, { variant: "outline", className: "mt-6 border-white text-black hover:bg-white hover:text-[#152D64]", onClick: () => setMode("login"), children: "Login Sekarang" })] })) })] })] }));
}
